# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\pyinterm\aldot_demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ALDOTDemo(object):
    def setupUi(self, ALDOTDemo):
        ALDOTDemo.setObjectName("ALDOTDemo")
        ALDOTDemo.resize(590, 283)
        self.centralwidget = QtWidgets.QWidget(ALDOTDemo)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_up.setObjectName("btn_up")
        self.gridLayout_2.addWidget(self.btn_up, 0, 0, 1, 1)
        self.btn_down = QtWidgets.QPushButton(self.centralwidget)
        self.btn_down.setObjectName("btn_down")
        self.gridLayout_2.addWidget(self.btn_down, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_ice = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_ice.setObjectName("cb_ice")
        self.verticalLayout.addWidget(self.cb_ice)
        self.cb_lemon = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_lemon.setObjectName("cb_lemon")
        self.verticalLayout.addWidget(self.cb_lemon)
        self.cb_sugar = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_sugar.setObjectName("cb_sugar")
        self.verticalLayout.addWidget(self.cb_sugar)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 1, 2, 1, 1)
        ALDOTDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ALDOTDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        ALDOTDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ALDOTDemo)
        self.statusbar.setObjectName("statusbar")
        ALDOTDemo.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(ALDOTDemo)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(ALDOTDemo)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCopy = QtWidgets.QAction(ALDOTDemo)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(ALDOTDemo)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCut = QtWidgets.QAction(ALDOTDemo)
        self.actionCut.setObjectName("actionCut")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionCut)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(ALDOTDemo)
        self.actionQuit.triggered.connect(ALDOTDemo.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ALDOTDemo)
        ALDOTDemo.setTabOrder(self.btn_up, self.btn_down)
        ALDOTDemo.setTabOrder(self.btn_down, self.lineEdit)
        ALDOTDemo.setTabOrder(self.lineEdit, self.cb_ice)
        ALDOTDemo.setTabOrder(self.cb_ice, self.cb_lemon)
        ALDOTDemo.setTabOrder(self.cb_lemon, self.cb_sugar)

    def retranslateUi(self, ALDOTDemo):
        _translate = QtCore.QCoreApplication.translate
        ALDOTDemo.setWindowTitle(_translate("ALDOTDemo", "ALDOT Demo"))
        self.btn_up.setToolTip(_translate("ALDOTDemo", "Go up, way up"))
        self.btn_up.setText(_translate("ALDOTDemo", "Up"))
        self.btn_down.setToolTip(_translate("ALDOTDemo", "Go down, way down"))
        self.btn_down.setText(_translate("ALDOTDemo", "Down"))
        self.cb_ice.setText(_translate("ALDOTDemo", "Ice"))
        self.cb_lemon.setText(_translate("ALDOTDemo", "Lemon"))
        self.cb_sugar.setText(_translate("ALDOTDemo", "Sugar"))
        self.menuFile.setTitle(_translate("ALDOTDemo", "File"))
        self.menuEdit.setTitle(_translate("ALDOTDemo", "Edit"))
        self.actionOpen.setText(_translate("ALDOTDemo", "Open"))
        self.actionQuit.setText(_translate("ALDOTDemo", "Quit"))
        self.actionCopy.setText(_translate("ALDOTDemo", "Copy"))
        self.actionPaste.setText(_translate("ALDOTDemo", "Paste"))
        self.actionCut.setText(_translate("ALDOTDemo", "Cut"))
